### ISSUE TITLE
Not working on Api 22

### ISSUE THREAD

**Issue by Tigersx** [SudarAbisheck/ZXing-Orient#11]
I can't get it to work on api 22, it works great on api 23 but I need to get it to work on api 22.
I get this error in cameraActivity Android: ContextCompat.getColor(context, R.color.my_color), cannot resolve “getColor”

**Comment by b1zantine** [comment]
`ContextCompat` is a class from the android support library. It might not have synced in properly. Did you try doing a clean gradle build?

**Comment by Tigersx** [comment]
Yes, I tried doing a clean gradle build.  The compile SDK version must match the support library's major version which is 23. I need it to compile with SdkVersion 22 which is not possbile unfortunately so i'll have to find a different scanner.

**Comment by b1zantine** [comment]
In that case use v2.0 of the library. It's built against api 22. https://github.com/SudarAbisheck/ZXing-Orient/tree/v2.0.0 
Pull the library using `compile 'me.sudar:zxing-orient:2.0.0@aar'`

**Comment by Tigersx** [comment]
Thanks, v2.0  works great!
